version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount the current directory into /app in the container
      - //var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket
