artifacts_root: artifacts

langchain_config:
  set_debug: False
  set_verbose: False
  recursion_limit: 50

terminal_config:
  root_dir: artifacts/terminal
  python_image: python:3.11-slim
  terminal_output_file: artifacts/terminal/output.json

llm_config:
  model: gemini-1.5-pro
  convert_system_message_to_human: True
  handle_parsing_errors: True
  max_tokens: 1000